{% set major_minor = "2.40" %}
{% set version = major_minor + ".1" %}
{% set sha256 = "4ad4abdd3258874f61c2e2a41d08e9930677976d303653cd1670d3e9f35463e9" %}
{% if linux %}
    {% set libext = ".so" %}
{% else %}
    {% set libext = ".dylib" %}
{% endif %}

package:
  name: libxmlpp
  version: {{ version }}

source:
  fn: libxml++-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/libxml++/{{ major_minor }}/libxml++-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - pkg-config
    - xz 5.2.*
    - glib 2.51.*
    - libsigcpp
    - libxml2 2.9.*
    - glibmm >=2.4
    - perl  # [linux]
  run:
    - glib 2.51.*
    - xz 5.2.*
    - libsigcpp
    - libxml2 2.9.*
    - glibmm >=2.4

test:
  commands:
    - test -f ${PREFIX}/lib/libxml++-2.6{{ libext }}

about:
  home: http://libxmlplusplus.sourceforge.net/
  license: GNU Lesser General Public License v2.1
  summary: "C++ bindings for libxml2"

extra:
  recipe-maintainers:
    - scopatz
