{% set version = "5.0.2" %}
{% set sha256 = "7c17cc3e5a2214314dee5a1354f4b436f266ded6185232a0534f352a76240d5a" %}
{% set major_minor = version.split(".")[:2] | join(".") %}

package:
  name: libxmlpp
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/libxml++/{{ major_minor }}/libxml++-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - perl >=5.20  # [linux]
  host:
    - xz
    - glib
    - sigcpp-2.0
    - libxml2
    - glibmm >=2.4
  run:
    - glibmm >=2.4

test:
  commands:
    - test -f ${PREFIX}/lib/libxml++-2.6{{ SHLIB_EXT }}

about:
  home: http://libxmlplusplus.sourceforge.net/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: C++ bindings for libxml2

extra:
  recipe-maintainers:
    - scopatz
