schema_version: 1

context:
  version: "5.4.0"
  major_minor: ${{ (version | split("."))[:2] | join(".") }}
  abi_version: "5.0"

recipe:
  name: libxmlpp-split
  version: ${{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/libxml++/${{ major_minor }}/libxml++-${{ version }}.tar.xz
  sha256: e9a23c436686a94698d2138e6bcbaf849121d63bfa0f50dc34fefbfd79566848

build:
  number: 3

outputs:

  # Performs the actual build - outputs
  # are inherited by packages below
  - staging:
      name: libxmlpp-build
    build:
      script: build_libxmlpp
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - xz-tools
        - meson
        - ninja
        - pkg-config
      host:
        - zlib
        - libxml2-devel
        - if: win
          then: liblzma-devel

  # ABI-specific runtime package
  - package:
      name: libxmlpp-${{ abi_version }}
    inherit: libxmlpp-build
    build:
      files:
        - if: win
          then: Library/bin/xml++-vc143-${{ abi_version }}-1.dll
        - if: linux
          then: lib/libxml++-${{ abi_version }}.so.*
        - if: osx
          then: lib/libxml++-${{ abi_version }}*.dylib
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - xz-tools
        - meson
        - ninja
        - pkg-config
      host:
        - zlib
        - libxml2-devel
        - if: win
          then: liblzma-devel
      run_exports:
        - ${{ pin_subpackage("libxmlpp-" ~ abi_version, upper_bound="x.x") }}
    tests:
      - package_contents:
          lib:
            - if: unix
              then: xml++-${{ abi_version }}
          files:
            - if: win
              then: Library/bin/xml++-vc143-${{ abi_version }}-1.dll

  # ABI-independent metapackage
  - package:
      name: libxmlpp
    requirements:
      run:
        - ${{ pin_subpackage("libxmlpp-" ~ abi_version, exact=True) }}

  # Development package
  - package:
      name: libxmlpp-devel
    inherit: libxmlpp-build
    build:
      files:
        - if: win
          then:
           - Library/lib/*
           - Library/include/*
        - if: osx
          then:
            - include/*
            - lib/libxml++-${{ abi_version }}/*
            - lib/pkgconfig/*
        - if: linux
          then:
            - include/*
            - lib/libxml++-${{ abi_version }}.so
            - lib/libxml++-${{ abi_version }}/*
            - lib/pkgconfig/*
    requirements:
      run:
        - ${{ pin_subpackage("libxmlpp", exact=True) }}
        - ${{ pin_subpackage("libxmlpp-" ~ abi_version, exact=True) }}
        - libxml2-devel
      run_exports:
        - ${{ pin_subpackage("libxmlpp", exact=True) }}
        - ${{ pin_subpackage("libxmlpp-" ~ abi_version, exact=True) }}      
    tests:
      - requirements:
          run:
            - pkg-config
        script:
          - env
          - pkg-config --exact-version=${{ version }} libxml++-${{ abi_version }}

about:
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: C++ bindings for libxml2-devel
  homepage: https://libxmlplusplus.github.io/libxmlplusplus/
  repository: https://github.com/libxmlplusplus/libxmlplusplus
  documentation: https://libxmlplusplus.github.io/libxmlplusplus/

extra:
  # conda-smithy otherwise names the feedstock after the first output
  feedstock-name: libxmlpp
  recipe-maintainers:
    - scopatz
    - pauldmccarthy
