travis:
  secure:
    BINSTAR_TOKEN: AfqUfds5vU0yt9uGtfEFdJW8VH7lgqzbuhZXsMQGERRBKarjeDJIuXhOObYki90Nvb0sfs3NwCeC4dNLVwFxnTapBvmIKSEbGU8HDFlmo+KyBCsCVQq00Yiaz/Us/v6l6drxmkXPPnZRoUmPGPidAAhIHE3kcMO2vbfcN1m++4wFp3vv8gIp9NfSVOXeoveMCf3+qRQkYLBOb3Cb1WJTBIwN1NlN4tHd2xJ06geyhiX/s19Y89n4/Q4cuj1Jem1rp0Sga5eikr+flm0j5jigqX8W/pjab+rErhNjPWkYDGJ3rnMaDqKGL28IsEd/HnO2MjfAQ1Rk24/GIdkIMRDBCW8N7MC8BywuVUwyaDDw9zy1uwcGoG2Yq+RbARuA24Mx+7fzmEXoqIl3GnAsviLiub4Dko+VDriCUNw37KtCAGsYuUA9g7/qsjuU+q1i9JFON0zocPWgQylItcppcxzSsBxybfdqOd2Le6d9Q8RDVW0PdKs6Y6uJNwXkvzGudsg2I53hNFjnAHOSNgrd1tJU46LcnmhdyANmtr5NMxp/uBxYqf4K1ZsUcuqm+fqkdBFs5KdOci4DitTM1/y+Wp36TuqTKJoXCJVoD9vvxVV1X+ur4cylEsJbXSU6yXoGtmGy+eD+2YPqQT7xBmVJmagIX8yplyQTAIK95KJ27Dlaei0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
