appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Im0Dofw9t4XkEdq+WePStSbwfJT4vgJznIHM/clM1JiRn+sT83D3ifo/5S/gqtX+9134eCc9CKSfT7AznFIjn4RDsFGOoLkiT61E4HxXVRERL2yRdz6Om5bs4WGTzVgUEzQRveJ2Ho5B4vWhg+MagdMHaZkY+mBgrvaczeeh2Lvskm7PXKEmmW11wfl4pqrJOdmwMNWvsQ3ss/LzDBKeiJ1UsV7sJjRU4HKzfuspV0tnO3JTLW4bsDZ+seNAHzw66wwsy93om3vf3XuyoO+m40IkkIyANwQzCAUNl5ELs1USyco6HQXr+vLuJOQ7+dHgZe+7EXBmbKw2ZrBd6oYAUDkSWxGVVaZEmCG9HS1w0pIJ3E8dOEex+Xs4W1wHTdXBKOXX82inSlYAKbQrGS44i/WcAHIoUq3H4L7bquJZt7Ana8fU2Ee8v+JcqS4Xq24wqHtNKgEWj51stpdB61co+xgaHDVrhuaQoMYjiAQloH6yvPGr6I4/+UFm8T9cuFd06ei03GoSTN6wY2JzUZ8IBPjeGO+iRCQ1tre2oQxu7sj6AxmraDyN6Q7N5+ZLTof+kvxZhHWkkuzJ1YZhGeE0nam1j5VBvzC+/yEFloj9KD8LLNEE8eEgmnjRBEnKTm/kUSIg8q3L1t8oqZPeOy4OtBfIpQY+y1QlOG/ANkE1zGc=}
